/****************************************************************************
**
** Metadata for AXVLC generated by dumpcpp from type library
** axvlc.dll
**
****************************************************************************/

#define QAX_DUMPCPP_AXVLC_NOINLINES
#include "axvlc.h"

using namespace AXVLC;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[213];
    char stringdata0[2460];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 18, 0),
QT_MOC_LITERAL(1, 19, 14, 0),
QT_MOC_LITERAL(2, 34, 0, 0),
QT_MOC_LITERAL(3, 35, 7, 0),
QT_MOC_LITERAL(4, 43, 9, 0),
QT_MOC_LITERAL(5, 53, 4, 0),
QT_MOC_LITERAL(6, 58, 6, 0),
QT_MOC_LITERAL(7, 65, 4, 0),
QT_MOC_LITERAL(8, 70, 4, 0),
QT_MOC_LITERAL(9, 75, 15, 0),
QT_MOC_LITERAL(10, 91, 4, 0),
QT_MOC_LITERAL(11, 96, 6, 0),
QT_MOC_LITERAL(12, 103, 4, 0),
QT_MOC_LITERAL(13, 108, 4, 0),
QT_MOC_LITERAL(14, 113, 11, 0),
QT_MOC_LITERAL(15, 125, 8, 0),
QT_MOC_LITERAL(16, 134, 11, 0),
QT_MOC_LITERAL(17, 146, 8, 0),
QT_MOC_LITERAL(18, 155, 6, 0),
QT_MOC_LITERAL(19, 162, 3, 0),
QT_MOC_LITERAL(20, 166, 11, 0),
QT_MOC_LITERAL(21, 178, 8, 0),
QT_MOC_LITERAL(22, 187, 7, 0),
QT_MOC_LITERAL(23, 195, 4, 0),
QT_MOC_LITERAL(24, 200, 10, 0),
QT_MOC_LITERAL(25, 211, 9, 0),
QT_MOC_LITERAL(26, 221, 6, 0),
QT_MOC_LITERAL(27, 228, 9, 0),
QT_MOC_LITERAL(28, 238, 3, 0),
QT_MOC_LITERAL(29, 242, 7, 0),
QT_MOC_LITERAL(30, 250, 15, 0),
QT_MOC_LITERAL(31, 266, 4, 0),
QT_MOC_LITERAL(32, 271, 10, 0),
QT_MOC_LITERAL(33, 282, 11, 0),
QT_MOC_LITERAL(34, 294, 5, 0),
QT_MOC_LITERAL(35, 300, 4, 0),
QT_MOC_LITERAL(36, 305, 10, 0),
QT_MOC_LITERAL(37, 316, 10, 0),
QT_MOC_LITERAL(38, 327, 13, 0),
QT_MOC_LITERAL(39, 341, 12, 0),
QT_MOC_LITERAL(40, 354, 12, 0),
QT_MOC_LITERAL(41, 367, 11, 0),
QT_MOC_LITERAL(42, 379, 5, 0),
QT_MOC_LITERAL(43, 385, 7, 0),
QT_MOC_LITERAL(44, 393, 7, 0),
QT_MOC_LITERAL(45, 401, 4, 0),
QT_MOC_LITERAL(46, 406, 10, 0),
QT_MOC_LITERAL(47, 417, 6, 0),
QT_MOC_LITERAL(48, 424, 7, 0),
QT_MOC_LITERAL(49, 432, 13, 0),
QT_MOC_LITERAL(50, 446, 13, 0),
QT_MOC_LITERAL(51, 460, 11, 0),
QT_MOC_LITERAL(52, 472, 7, 0),
QT_MOC_LITERAL(53, 480, 17, 0),
QT_MOC_LITERAL(54, 498, 22, 0),
QT_MOC_LITERAL(55, 521, 18, 0),
QT_MOC_LITERAL(56, 540, 23, 0),
QT_MOC_LITERAL(57, 564, 17, 0),
QT_MOC_LITERAL(58, 582, 22, 0),
QT_MOC_LITERAL(59, 605, 22, 0),
QT_MOC_LITERAL(60, 628, 18, 0),
QT_MOC_LITERAL(61, 647, 23, 0),
QT_MOC_LITERAL(62, 671, 19, 0),
QT_MOC_LITERAL(63, 691, 24, 0),
QT_MOC_LITERAL(64, 716, 18, 0),
QT_MOC_LITERAL(65, 735, 23, 0),
QT_MOC_LITERAL(66, 759, 23, 0),
QT_MOC_LITERAL(67, 783, 16, 0),
QT_MOC_LITERAL(68, 800, 11, 0),
QT_MOC_LITERAL(69, 812, 7, 0),
QT_MOC_LITERAL(70, 820, 10, 0),
QT_MOC_LITERAL(71, 831, 7, 0),
QT_MOC_LITERAL(72, 839, 7, 0),
QT_MOC_LITERAL(73, 847, 4, 0),
QT_MOC_LITERAL(74, 852, 8, 0),
QT_MOC_LITERAL(75, 861, 5, 0),
QT_MOC_LITERAL(76, 867, 5, 0),
QT_MOC_LITERAL(77, 873, 16, 0),
QT_MOC_LITERAL(78, 890, 7, 0),
QT_MOC_LITERAL(79, 898, 4, 0),
QT_MOC_LITERAL(80, 903, 3, 0),
QT_MOC_LITERAL(81, 907, 7, 0),
QT_MOC_LITERAL(82, 915, 5, 0),
QT_MOC_LITERAL(83, 921, 15, 0),
QT_MOC_LITERAL(84, 937, 7, 0),
QT_MOC_LITERAL(85, 945, 6, 0),
QT_MOC_LITERAL(86, 952, 4, 0),
QT_MOC_LITERAL(87, 957, 5, 0),
QT_MOC_LITERAL(88, 963, 8, 0),
QT_MOC_LITERAL(89, 972, 5, 0),
QT_MOC_LITERAL(90, 978, 10, 0),
QT_MOC_LITERAL(91, 989, 7, 0),
QT_MOC_LITERAL(92, 997, 9, 0),
QT_MOC_LITERAL(93, 1007, 6, 0),
QT_MOC_LITERAL(94, 1014, 4, 0),
QT_MOC_LITERAL(95, 1019, 1, 0),
QT_MOC_LITERAL(96, 1021, 4, 0),
QT_MOC_LITERAL(97, 1026, 1, 0),
QT_MOC_LITERAL(98, 1028, 22, 0),
QT_MOC_LITERAL(99, 1051, 18, 0),
QT_MOC_LITERAL(100, 1070, 8, 0),
QT_MOC_LITERAL(101, 1079, 5, 0),
QT_MOC_LITERAL(102, 1085, 10, 0),
QT_MOC_LITERAL(103, 1096, 7, 0),
QT_MOC_LITERAL(104, 1104, 7, 0),
QT_MOC_LITERAL(105, 1112, 4, 0),
QT_MOC_LITERAL(106, 1117, 7, 0),
QT_MOC_LITERAL(107, 1125, 4, 0),
QT_MOC_LITERAL(108, 1130, 10, 0),
QT_MOC_LITERAL(109, 1141, 7, 0),
QT_MOC_LITERAL(110, 1149, 19, 0),
QT_MOC_LITERAL(111, 1169, 3, 0),
QT_MOC_LITERAL(112, 1173, 5, 0),
QT_MOC_LITERAL(113, 1179, 4, 0),
QT_MOC_LITERAL(114, 1184, 8, 0),
QT_MOC_LITERAL(115, 1193, 6, 0),
QT_MOC_LITERAL(116, 1200, 4, 0),
QT_MOC_LITERAL(117, 1205, 10, 0),
QT_MOC_LITERAL(118, 1216, 4, 0),
QT_MOC_LITERAL(119, 1221, 11, 0),
QT_MOC_LITERAL(120, 1233, 9, 0),
QT_MOC_LITERAL(121, 1243, 9, 0),
QT_MOC_LITERAL(122, 1253, 5, 0),
QT_MOC_LITERAL(123, 1259, 18, 0),
QT_MOC_LITERAL(124, 1278, 24, 0),
QT_MOC_LITERAL(125, 1303, 6, 0),
QT_MOC_LITERAL(126, 1310, 19, 0),
QT_MOC_LITERAL(127, 1330, 6, 0),
QT_MOC_LITERAL(128, 1337, 16, 0),
QT_MOC_LITERAL(129, 1354, 14, 0),
QT_MOC_LITERAL(130, 1369, 11, 0),
QT_MOC_LITERAL(131, 1381, 7, 0),
QT_MOC_LITERAL(132, 1389, 4, 0),
QT_MOC_LITERAL(133, 1394, 13, 0),
QT_MOC_LITERAL(134, 1408, 11, 0),
QT_MOC_LITERAL(135, 1420, 8, 0),
QT_MOC_LITERAL(136, 1429, 11, 0),
QT_MOC_LITERAL(137, 1441, 8, 0),
QT_MOC_LITERAL(138, 1450, 12, 0),
QT_MOC_LITERAL(139, 1463, 13, 0),
QT_MOC_LITERAL(140, 1477, 16, 0),
QT_MOC_LITERAL(141, 1494, 14, 0),
QT_MOC_LITERAL(142, 1509, 11, 0),
QT_MOC_LITERAL(143, 1521, 16, 0),
QT_MOC_LITERAL(144, 1538, 6, 0),
QT_MOC_LITERAL(145, 1545, 4, 0),
QT_MOC_LITERAL(146, 1550, 9, 0),
QT_MOC_LITERAL(147, 1560, 7, 0),
QT_MOC_LITERAL(148, 1568, 12, 0),
QT_MOC_LITERAL(149, 1581, 5, 0),
QT_MOC_LITERAL(150, 1587, 19, 0),
QT_MOC_LITERAL(151, 1607, 12, 0),
QT_MOC_LITERAL(152, 1620, 9, 0),
QT_MOC_LITERAL(153, 1630, 10, 0),
QT_MOC_LITERAL(154, 1641, 7, 0),
QT_MOC_LITERAL(155, 1649, 20, 0),
QT_MOC_LITERAL(156, 1670, 17, 0),
QT_MOC_LITERAL(157, 1688, 12, 0),
QT_MOC_LITERAL(158, 1701, 9, 0),
QT_MOC_LITERAL(159, 1711, 10, 0),
QT_MOC_LITERAL(160, 1722, 7, 0),
QT_MOC_LITERAL(161, 1730, 5, 0),
QT_MOC_LITERAL(162, 1736, 10, 0),
QT_MOC_LITERAL(163, 1747, 5, 0),
QT_MOC_LITERAL(164, 1753, 10, 0),
QT_MOC_LITERAL(165, 1764, 16, 0),
QT_MOC_LITERAL(166, 1781, 21, 0),
QT_MOC_LITERAL(167, 1803, 8, 0),
QT_MOC_LITERAL(168, 1812, 13, 0),
QT_MOC_LITERAL(169, 1826, 13, 0),
QT_MOC_LITERAL(170, 1840, 5, 0),
QT_MOC_LITERAL(171, 1846, 10, 0),
QT_MOC_LITERAL(172, 1857, 27, 0),
QT_MOC_LITERAL(173, 1885, 5, 0),
QT_MOC_LITERAL(174, 1891, 6, 0),
QT_MOC_LITERAL(175, 1898, 10, 0),
QT_MOC_LITERAL(176, 1909, 9, 0),
QT_MOC_LITERAL(177, 1919, 4, 0),
QT_MOC_LITERAL(178, 1924, 9, 0),
QT_MOC_LITERAL(179, 1934, 5, 0),
QT_MOC_LITERAL(180, 1940, 8, 0),
QT_MOC_LITERAL(181, 1949, 10, 0),
QT_MOC_LITERAL(182, 1960, 9, 0),
QT_MOC_LITERAL(183, 1970, 6, 0),
QT_MOC_LITERAL(184, 1977, 7, 0),
QT_MOC_LITERAL(185, 1985, 5, 0),
QT_MOC_LITERAL(186, 1991, 11, 0),
QT_MOC_LITERAL(187, 2003, 3, 0),
QT_MOC_LITERAL(188, 2007, 16, 0),
QT_MOC_LITERAL(189, 2024, 17, 0),
QT_MOC_LITERAL(190, 2042, 10, 0),
QT_MOC_LITERAL(191, 2053, 11, 0),
QT_MOC_LITERAL(192, 2065, 11, 0),
QT_MOC_LITERAL(193, 2077, 11, 0),
QT_MOC_LITERAL(194, 2089, 12, 0),
QT_MOC_LITERAL(195, 2102, 19, 0),
QT_MOC_LITERAL(196, 2122, 20, 0),
QT_MOC_LITERAL(197, 2143, 5, 0),
QT_MOC_LITERAL(198, 2149, 27, 0),
QT_MOC_LITERAL(199, 2177, 21, 0),
QT_MOC_LITERAL(200, 2199, 18, 0),
QT_MOC_LITERAL(201, 2218, 25, 0),
QT_MOC_LITERAL(202, 2244, 18, 0),
QT_MOC_LITERAL(203, 2263, 26, 0),
QT_MOC_LITERAL(204, 2290, 8, 0),
QT_MOC_LITERAL(205, 2299, 17, 0),
QT_MOC_LITERAL(206, 2317, 18, 0),
QT_MOC_LITERAL(207, 2336, 26, 0),
QT_MOC_LITERAL(208, 2363, 26, 0),
QT_MOC_LITERAL(209, 2390, 8, 0),
QT_MOC_LITERAL(210, 2399, 18, 0),
QT_MOC_LITERAL(211, 2418, 22, 0),
QT_MOC_LITERAL(212, 2441, 17, 0)
    },
    "AXVLC::IVLCControl\0VisibleChanged\0\0Visible\0exception\0code\0source\0disc\0help\0"
    "propertyChanged\0name\0signal\0argc\0argv\0SetAutoLoop\0AutoLoop\0SetAutoPlay\0"
    "AutoPlay\0SetMRL\0MRL\0SetPosition\0Position\0SetTime\0Time\0SetVisible\0SetVolume\0"
    "Volume\0addTarget\0uri\0options\0VLCPlaylistMode\0mode\0fullscreen\0getVariable\0"
    "pause\0play\0playFaster\0playSlower\0playlistClear\0playlistNext\0playlistPrev\0"
    "setVariable\0value\0shuttle\0seconds\0stop\0toggleMute\0Length\0Playing\0PlaylistCount\0"
    "PlaylistIndex\0VersionInfo\0control\0VLCPlayListInsert\0VLCPlayListInsertAndGo\0"
    "VLCPlayListReplace\0VLCPlayListReplaceAndGo\0VLCPlayListAppend\0VLCPlayListAppendAndGo\0"
    "VLCPlayListCheckInsert\0VLCPlayListInsert1\0VLCPlayListInsertAndGo2\0"
    "VLCPlayListReplace3\0VLCPlayListReplaceAndGo4\0VLCPlayListAppend5\0"
    "VLCPlayListAppendAndGo6\0VLCPlayListCheckInsert7\0AXVLC::IVLCAudio\0description\0"
    "trackID\0setChannel\0channel\0setMute\0mute\0setTrack\0track\0count\0AXVLC::IVLCInput\0"
    "setRate\0rate\0fps\0hasVout\0state\0AXVLC::IVLCLogo\0disable\0enable\0file\0fname\0"
    "setDelay\0delay\0setOpacity\0opacity\0setRepeat\0repeat\0setX\0x\0setY\0y\0"
    "AXVLC::IVLCDeinterlace\0AXVLC::IVLCMarquee\0setColor\0color\0setRefresh\0refresh\0"
    "setSize\0size\0setText\0text\0setTimeout\0timeout\0AXVLC::IVLCPlaylist\0add\0clear\0"
    "next\0playItem\0itemId\0prev\0removeItem\0item\0togglePause\0isPlaying\0itemCount\0"
    "items\0IVLCPlaylistItems*\0AXVLC::IVLCPlaylistItems\0remove\0AXVLC::IVLCSubtitle\0"
    "nameID\0AXVLC::IVLCVideo\0setAspectRatio\0aspectRatio\0setCrop\0crop\0setFullscreen\0"
    "setSubtitle\0subtitle\0setTeletext\0teletext\0takeSnapshot\0IPictureDisp*\0"
    "toggleFullscreen\0toggleTeletext\0deinterlace\0IVLCDeinterlace*\0height\0logo\0"
    "IVLCLogo*\0marquee\0IVLCMarquee*\0width\0AXVLC::IVLCControl2\0SetBackColor\0BackColor\0"
    "SetBaseURL\0BaseURL\0SetFullscreenEnabled\0FullscreenEnabled\0SetStartTime\0"
    "StartTime\0SetToolbar\0Toolbar\0audio\0IVLCAudio*\0input\0IVLCInput*\0mediaDescription\0"
    "IVLCMediaDescription*\0playlist\0IVLCPlaylist*\0IVLCSubtitle*\0video\0IVLCVideo*\0"
    "AXVLC::IVLCMediaDescription\0album\0artist\0artworkURL\0copyright\0date\0encodedBy\0"
    "genre\0language\0nowPlaying\0publisher\0rating\0setting\0title\0trackNumber\0url\0"
    "AXVLC::VLCPlugin\0Event Interface 2\0DVLCEvents\0Interface 0\0IVLCControl\0"
    "Interface 1\0IVLCControl2\0MediaPlayerBackward\0MediaPlayerBuffering\0cache\0"
    "MediaPlayerEncounteredError\0MediaPlayerEndReached\0MediaPlayerForward\0"
    "MediaPlayerNothingSpecial\0MediaPlayerOpening\0MediaPlayerPausableChanged\0"
    "pausable\0MediaPlayerPaused\0MediaPlayerPlaying\0MediaPlayerPositionChanged\0"
    "MediaPlayerSeekableChanged\0seekable\0MediaPlayerStopped\0MediaPlayerTimeChanged\0"
    "AXVLC::VLCPlugin2\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_AXVLC__IVLCControl[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    25, 14, // methods
    13, 212, // properties
    1, 251, // enums/sets
    0, 0, // constructors
    0, // flags
    4, // signal count

// signal: name, argc, parameters, tag, flags
    1, 1, 139, 2, 5,
    4, 4, 142, 2, 5,
    9, 1, 151, 2, 5,
    11, 3, 154, 2, 5,

// slot: name, argc, parameters, tag, flags
    14, 1, 161, 2, 9,
    16, 1, 164, 2, 9,
    18, 1, 167, 2, 9,
    20, 1, 170, 2, 9,
    22, 1, 173, 2, 9,
    24, 1, 176, 2, 9,
    25, 1, 179, 2, 9,
    27, 4, 182, 2, 9,
    32, 0, 191, 2, 9,
    33, 1, 192, 2, 9,
    34, 0, 195, 2, 9,
    35, 0, 196, 2, 9,
    36, 0, 197, 2, 9,
    37, 0, 198, 2, 9,
    38, 0, 199, 2, 9,
    39, 0, 200, 2, 9,
    40, 0, 201, 2, 9,
    41, 2, 202, 2, 9,
    43, 1, 207, 2, 9,
    45, 0, 210, 2, 9,
    46, 0, 211, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Bool, 3,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 15,
    QMetaType::Void, QMetaType::Bool, 17,
    QMetaType::Void, QMetaType::QString, 19,
    QMetaType::Void, QMetaType::Double, 21,
    QMetaType::Void, QMetaType::Int, 23,
    QMetaType::Void, QMetaType::Bool, 3,
    QMetaType::Void, QMetaType::Int, 26,
    QMetaType::Void, QMetaType::QString, QMetaType::QVariant, 0x80000000 | 30, QMetaType::Int, 28, 29, 31, 21,
    QMetaType::Void,
    QMetaType::QVariant, QMetaType::QString, 10,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, QMetaType::QVariant, 10, 42,
    QMetaType::Void, QMetaType::Int, 44,
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    15, QMetaType::Bool, 0x01015003, 		 // bool AutoLoop
    17, QMetaType::Bool, 0x01015003, 		 // bool AutoPlay
    47, QMetaType::Int, 0x02004001, 		 // int Length
    19, QMetaType::QString, 0x0a015003, 		 // QString MRL
    48, QMetaType::Bool, 0x01004001, 		 // bool Playing
    49, QMetaType::Int, 0x02005001, 		 // int PlaylistCount
    50, QMetaType::Int, 0x02005001, 		 // int PlaylistIndex
    21, QMetaType::Double, 0x06015003, 		 // double Position
    23, QMetaType::Int, 0x02015003, 		 // int Time
    51, QMetaType::QString, 0x0a004001, 		 // QString VersionInfo
    3, QMetaType::Bool, 0x01015003, 		 // bool Visible
    26, QMetaType::Int, 0x02015003, 		 // int Volume
    52, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    30, 0x0, 14, 255, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject IVLCControl::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__IVLCControl, 0, 0, 0 }
};

void *IVLCControl::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::IVLCControl"))
        return static_cast<void*>(const_cast<IVLCControl*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__IVLCAudio[] = {

 // content:
    7, // revision
    67,  // classname
    0, 0, // classinfo
    9, 14, // methods
    6, 94, // properties
    1, 112, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    4, 4, 59, 2, 5,
    9, 1, 68, 2, 5,
    11, 3, 71, 2, 5,

// slot: name, argc, parameters, tag, flags
    25, 1, 78, 2, 9,
    68, 1, 81, 2, 9,
    70, 1, 84, 2, 9,
    72, 1, 87, 2, 9,
    74, 1, 90, 2, 9,
    46, 0, 93, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::Int, 26,
    QMetaType::QString, QMetaType::Int, 69,
    QMetaType::Void, QMetaType::Int, 71,
    QMetaType::Void, QMetaType::Bool, 73,
    QMetaType::Void, QMetaType::Int, 75,
    QMetaType::Void,

 // properties: name, type, flags
    26, QMetaType::Int, 0x02015003, 		 // int Volume
    71, QMetaType::Int, 0x02015003, 		 // int channel
    52, QMetaType::QString, 0x0a055003, 		 // QString control
    76, QMetaType::Int, 0x02005001, 		 // int count
    73, QMetaType::Bool, 0x01015003, 		 // bool mute
    75, QMetaType::Int, 0x02015003, 		 // int track

 // enums: name, flags, count, data
    30, 0x0, 14, 116, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject IVLCAudio::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__IVLCAudio, 0, 0, 0 }
};

void *IVLCAudio::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::IVLCAudio"))
        return static_cast<void*>(const_cast<IVLCAudio*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__IVLCInput[] = {

 // content:
    7, // revision
    77,  // classname
    0, 0, // classinfo
    6, 14, // methods
    8, 72, // properties
    1, 96, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    4, 4, 44, 2, 5,
    9, 1, 53, 2, 5,
    11, 3, 56, 2, 5,

// slot: name, argc, parameters, tag, flags
    20, 1, 63, 2, 9,
    22, 1, 66, 2, 9,
    78, 1, 69, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::Double, 21,
    QMetaType::Void, QMetaType::Double, 23,
    QMetaType::Void, QMetaType::Double, 79,

 // properties: name, type, flags
    47, QMetaType::Double, 0x06005001, 		 // double Length
    21, QMetaType::Double, 0x06015003, 		 // double Position
    23, QMetaType::Double, 0x06015003, 		 // double Time
    52, QMetaType::QString, 0x0a055003, 		 // QString control
    80, QMetaType::Double, 0x06005001, 		 // double fps
    81, QMetaType::Bool, 0x01005001, 		 // bool hasVout
    79, QMetaType::Double, 0x06015003, 		 // double rate
    82, QMetaType::Int, 0x02005001, 		 // int state

 // enums: name, flags, count, data
    30, 0x0, 14, 100, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject IVLCInput::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__IVLCInput, 0, 0, 0 }
};

void *IVLCInput::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::IVLCInput"))
        return static_cast<void*>(const_cast<IVLCInput*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__IVLCLogo[] = {

 // content:
    7, // revision
    83,  // classname
    0, 0, // classinfo
    12, 14, // methods
    7, 116, // properties
    1, 137, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    4, 4, 74, 2, 5,
    9, 1, 83, 2, 5,
    11, 3, 86, 2, 5,

// slot: name, argc, parameters, tag, flags
    20, 1, 93, 2, 9,
    84, 0, 96, 2, 9,
    85, 0, 97, 2, 9,
    86, 1, 98, 2, 9,
    88, 1, 101, 2, 9,
    90, 1, 104, 2, 9,
    92, 1, 107, 2, 9,
    94, 1, 110, 2, 9,
    96, 1, 113, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::QString, 21,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 87,
    QMetaType::Void, QMetaType::Int, 89,
    QMetaType::Void, QMetaType::Int, 91,
    QMetaType::Void, QMetaType::Int, 93,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::Int, 97,

 // properties: name, type, flags
    21, QMetaType::QString, 0x0a015003, 		 // QString Position
    52, QMetaType::QString, 0x0a055003, 		 // QString control
    89, QMetaType::Int, 0x02015003, 		 // int delay
    91, QMetaType::Int, 0x02015003, 		 // int opacity
    93, QMetaType::Int, 0x02015003, 		 // int repeat
    95, QMetaType::Int, 0x02015003, 		 // int x
    97, QMetaType::Int, 0x02015003, 		 // int y

 // enums: name, flags, count, data
    30, 0x0, 14, 141, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject IVLCLogo::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__IVLCLogo, 0, 0, 0 }
};

void *IVLCLogo::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::IVLCLogo"))
        return static_cast<void*>(const_cast<IVLCLogo*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__IVLCDeinterlace[] = {

 // content:
    7, // revision
    98,  // classname
    0, 0, // classinfo
    5, 14, // methods
    1, 62, // properties
    1, 65, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    4, 4, 39, 2, 5,
    9, 1, 48, 2, 5,
    11, 3, 51, 2, 5,

// slot: name, argc, parameters, tag, flags
    84, 0, 58, 2, 9,
    85, 1, 59, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 31,

 // properties: name, type, flags
    52, QMetaType::QString, 0x0a055003, 		 // QString control

 // enums: name, flags, count, data
    30, 0x0, 14, 69, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject IVLCDeinterlace::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__IVLCDeinterlace, 0, 0, 0 }
};

void *IVLCDeinterlace::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::IVLCDeinterlace"))
        return static_cast<void*>(const_cast<IVLCDeinterlace*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__IVLCMarquee[] = {

 // content:
    7, // revision
    99,  // classname
    0, 0, // classinfo
    14, 14, // methods
    10, 132, // properties
    1, 162, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    4, 4, 84, 2, 5,
    9, 1, 93, 2, 5,
    11, 3, 96, 2, 5,

// slot: name, argc, parameters, tag, flags
    20, 1, 103, 2, 9,
    84, 0, 106, 2, 9,
    85, 0, 107, 2, 9,
    100, 1, 108, 2, 9,
    90, 1, 111, 2, 9,
    102, 1, 114, 2, 9,
    104, 1, 117, 2, 9,
    106, 1, 120, 2, 9,
    108, 1, 123, 2, 9,
    94, 1, 126, 2, 9,
    96, 1, 129, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::QString, 21,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 101,
    QMetaType::Void, QMetaType::Int, 91,
    QMetaType::Void, QMetaType::Int, 103,
    QMetaType::Void, QMetaType::Int, 105,
    QMetaType::Void, QMetaType::QString, 107,
    QMetaType::Void, QMetaType::Int, 109,
    QMetaType::Void, QMetaType::Int, 95,
    QMetaType::Void, QMetaType::Int, 97,

 // properties: name, type, flags
    21, QMetaType::QString, 0x0a015003, 		 // QString Position
    101, QMetaType::Int, 0x02015003, 		 // int color
    52, QMetaType::QString, 0x0a055003, 		 // QString control
    91, QMetaType::Int, 0x02015003, 		 // int opacity
    103, QMetaType::Int, 0x02015003, 		 // int refresh
    105, QMetaType::Int, 0x02015003, 		 // int size
    107, QMetaType::QString, 0x0a015003, 		 // QString text
    109, QMetaType::Int, 0x02015003, 		 // int timeout
    95, QMetaType::Int, 0x02015003, 		 // int x
    97, QMetaType::Int, 0x02015003, 		 // int y

 // enums: name, flags, count, data
    30, 0x0, 14, 166, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject IVLCMarquee::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__IVLCMarquee, 0, 0, 0 }
};

void *IVLCMarquee::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::IVLCMarquee"))
        return static_cast<void*>(const_cast<IVLCMarquee*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__IVLCPlaylist[] = {

 // content:
    7, // revision
    110,  // classname
    0, 0, // classinfo
    15, 14, // methods
    4, 136, // properties
    1, 148, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    4, 4, 89, 2, 5,
    9, 1, 98, 2, 5,
    11, 3, 101, 2, 5,

// slot: name, argc, parameters, tag, flags
    111, 1, 108, 2, 11,
    111, 2, 111, 2, 11,
    111, 3, 116, 2, 9,
    112, 0, 123, 2, 9,
    113, 0, 124, 2, 9,
    34, 0, 125, 2, 9,
    35, 0, 126, 2, 9,
    114, 1, 127, 2, 9,
    116, 0, 130, 2, 9,
    117, 1, 131, 2, 9,
    45, 0, 134, 2, 9,
    119, 0, 135, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Int, QMetaType::QString, 28,
    QMetaType::Int, QMetaType::QString, QMetaType::QVariant, 28, 10,
    QMetaType::Int, QMetaType::QString, QMetaType::QVariant, QMetaType::QVariant, 28, 10, 29,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 115,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 118,
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    52, QMetaType::QString, 0x0a055003, 		 // QString control
    120, QMetaType::Bool, 0x01005001, 		 // bool isPlaying
    121, QMetaType::Int, 0x02004001, 		 // int itemCount
    122, 0x80000000 | 123, 0x00005001, 		 // IVLCPlaylistItems* items

 // enums: name, flags, count, data
    30, 0x0, 14, 152, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject IVLCPlaylist::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__IVLCPlaylist, 0, 0, 0 }
};

void *IVLCPlaylist::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::IVLCPlaylist"))
        return static_cast<void*>(const_cast<IVLCPlaylist*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__IVLCPlaylistItems[] = {

 // content:
    7, // revision
    124,  // classname
    0, 0, // classinfo
    5, 14, // methods
    2, 62, // properties
    1, 68, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    4, 4, 39, 2, 5,
    9, 1, 48, 2, 5,
    11, 3, 51, 2, 5,

// slot: name, argc, parameters, tag, flags
    112, 0, 58, 2, 9,
    125, 1, 59, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 115,

 // properties: name, type, flags
    52, QMetaType::QString, 0x0a055003, 		 // QString control
    76, QMetaType::Int, 0x02005001, 		 // int count

 // enums: name, flags, count, data
    30, 0x0, 14, 72, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject IVLCPlaylistItems::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__IVLCPlaylistItems, 0, 0, 0 }
};

void *IVLCPlaylistItems::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::IVLCPlaylistItems"))
        return static_cast<void*>(const_cast<IVLCPlaylistItems*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__IVLCSubtitle[] = {

 // content:
    7, // revision
    126,  // classname
    0, 0, // classinfo
    5, 14, // methods
    3, 64, // properties
    1, 73, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    4, 4, 39, 2, 5,
    9, 1, 48, 2, 5,
    11, 3, 51, 2, 5,

// slot: name, argc, parameters, tag, flags
    68, 1, 58, 2, 9,
    74, 1, 61, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::QString, QMetaType::Int, 127,
    QMetaType::Void, QMetaType::Int, 75,

 // properties: name, type, flags
    52, QMetaType::QString, 0x0a055003, 		 // QString control
    76, QMetaType::Int, 0x02005001, 		 // int count
    75, QMetaType::Int, 0x02015003, 		 // int track

 // enums: name, flags, count, data
    30, 0x0, 14, 77, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject IVLCSubtitle::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__IVLCSubtitle, 0, 0, 0 }
};

void *IVLCSubtitle::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::IVLCSubtitle"))
        return static_cast<void*>(const_cast<IVLCSubtitle*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__IVLCVideo[] = {

 // content:
    7, // revision
    128,  // classname
    0, 0, // classinfo
    11, 14, // methods
    11, 106, // properties
    1, 139, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    4, 4, 69, 2, 5,
    9, 1, 78, 2, 5,
    11, 3, 81, 2, 5,

// slot: name, argc, parameters, tag, flags
    129, 1, 88, 2, 9,
    131, 1, 91, 2, 9,
    133, 1, 94, 2, 9,
    134, 1, 97, 2, 9,
    136, 1, 100, 2, 9,
    138, 0, 103, 2, 9,
    140, 0, 104, 2, 9,
    141, 0, 105, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::QString, 130,
    QMetaType::Void, QMetaType::QString, 132,
    QMetaType::Void, QMetaType::Bool, 32,
    QMetaType::Void, QMetaType::Int, 135,
    QMetaType::Void, QMetaType::Int, 137,
    0x80000000 | 139,
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    130, QMetaType::QString, 0x0a015003, 		 // QString aspectRatio
    52, QMetaType::QString, 0x0a055003, 		 // QString control
    132, QMetaType::QString, 0x0a015003, 		 // QString crop
    142, 0x80000000 | 143, 0x00005001, 		 // IVLCDeinterlace* deinterlace
    32, QMetaType::Bool, 0x01015003, 		 // bool fullscreen
    144, QMetaType::Int, 0x02005001, 		 // int height
    145, 0x80000000 | 146, 0x00005001, 		 // IVLCLogo* logo
    147, 0x80000000 | 148, 0x00005001, 		 // IVLCMarquee* marquee
    135, QMetaType::Int, 0x02015003, 		 // int subtitle
    137, QMetaType::Int, 0x02015003, 		 // int teletext
    149, QMetaType::Int, 0x02005001, 		 // int width

 // enums: name, flags, count, data
    30, 0x0, 14, 143, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject IVLCVideo::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__IVLCVideo, 0, 0, 0 }
};

void *IVLCVideo::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::IVLCVideo"))
        return static_cast<void*>(const_cast<IVLCVideo*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__IVLCControl2[] = {

 // content:
    7, // revision
    150,  // classname
    0, 0, // classinfo
    13, 14, // methods
    18, 128, // properties
    1, 182, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    4, 4, 79, 2, 5,
    9, 1, 88, 2, 5,
    11, 3, 91, 2, 5,

// slot: name, argc, parameters, tag, flags
    14, 1, 98, 2, 9,
    16, 1, 101, 2, 9,
    151, 1, 104, 2, 9,
    153, 1, 107, 2, 9,
    155, 1, 110, 2, 9,
    18, 1, 113, 2, 9,
    157, 1, 116, 2, 9,
    159, 1, 119, 2, 9,
    24, 1, 122, 2, 9,
    25, 1, 125, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 15,
    QMetaType::Void, QMetaType::Bool, 17,
    QMetaType::Void, QMetaType::UInt, 152,
    QMetaType::Void, QMetaType::QString, 154,
    QMetaType::Void, QMetaType::Bool, 156,
    QMetaType::Void, QMetaType::QString, 19,
    QMetaType::Void, QMetaType::Int, 158,
    QMetaType::Void, QMetaType::Bool, 160,
    QMetaType::Void, QMetaType::Bool, 3,
    QMetaType::Void, QMetaType::Int, 26,

 // properties: name, type, flags
    15, QMetaType::Bool, 0x01015003, 		 // bool AutoLoop
    17, QMetaType::Bool, 0x01015003, 		 // bool AutoPlay
    152, QMetaType::UInt, 0x03015003, 		 // uint BackColor
    154, QMetaType::QString, 0x0a015003, 		 // QString BaseURL
    156, QMetaType::Bool, 0x01015003, 		 // bool FullscreenEnabled
    19, QMetaType::QString, 0x0a015003, 		 // QString MRL
    158, QMetaType::Int, 0x02015003, 		 // int StartTime
    160, QMetaType::Bool, 0x01015003, 		 // bool Toolbar
    51, QMetaType::QString, 0x0a005001, 		 // QString VersionInfo
    3, QMetaType::Bool, 0x01015003, 		 // bool Visible
    26, QMetaType::Int, 0x02015003, 		 // int Volume
    161, 0x80000000 | 162, 0x00005001, 		 // IVLCAudio* audio
    52, QMetaType::QString, 0x0a055003, 		 // QString control
    163, 0x80000000 | 164, 0x00005001, 		 // IVLCInput* input
    165, 0x80000000 | 166, 0x00005001, 		 // IVLCMediaDescription* mediaDescription
    167, 0x80000000 | 168, 0x00005001, 		 // IVLCPlaylist* playlist
    135, 0x80000000 | 169, 0x00005001, 		 // IVLCSubtitle* subtitle
    170, 0x80000000 | 171, 0x00005001, 		 // IVLCVideo* video

 // enums: name, flags, count, data
    30, 0x0, 14, 186, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject IVLCControl2::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__IVLCControl2, 0, 0, 0 }
};

void *IVLCControl2::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::IVLCControl2"))
        return static_cast<void*>(const_cast<IVLCControl2*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__IVLCMediaDescription[] = {

 // content:
    7, // revision
    172,  // classname
    0, 0, // classinfo
    3, 14, // methods
    18, 48, // properties
    1, 102, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    4, 4, 29, 2, 5,
    9, 1, 38, 2, 5,
    11, 3, 41, 2, 5,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,

 // properties: name, type, flags
    173, QMetaType::QString, 0x0a005001, 		 // QString album
    174, QMetaType::QString, 0x0a005001, 		 // QString artist
    175, QMetaType::QString, 0x0a005001, 		 // QString artworkURL
    52, QMetaType::QString, 0x0a055003, 		 // QString control
    176, QMetaType::QString, 0x0a005001, 		 // QString copyright
    177, QMetaType::QString, 0x0a005001, 		 // QString date
    68, QMetaType::QString, 0x0a005001, 		 // QString description
    178, QMetaType::QString, 0x0a005001, 		 // QString encodedBy
    179, QMetaType::QString, 0x0a005001, 		 // QString genre
    180, QMetaType::QString, 0x0a005001, 		 // QString language
    181, QMetaType::QString, 0x0a005001, 		 // QString nowPlaying
    182, QMetaType::QString, 0x0a005001, 		 // QString publisher
    183, QMetaType::QString, 0x0a005001, 		 // QString rating
    184, QMetaType::QString, 0x0a005001, 		 // QString setting
    185, QMetaType::QString, 0x0a005001, 		 // QString title
    69, QMetaType::QString, 0x0a005001, 		 // QString trackID
    186, QMetaType::QString, 0x0a005001, 		 // QString trackNumber
    187, QMetaType::QString, 0x0a005001, 		 // QString url

 // enums: name, flags, count, data
    30, 0x0, 14, 106, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject IVLCMediaDescription::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__IVLCMediaDescription, 0, 0, 0 }
};

void *IVLCMediaDescription::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::IVLCMediaDescription"))
        return static_cast<void*>(const_cast<IVLCMediaDescription*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__VLCPlugin[] = {

 // content:
    7, // revision
    188,  // classname
    3, 14, // classinfo
    47, 20, // methods
    23, 370, // properties
    1, 439, // enums/sets
    0, 0, // constructors
    0, // flags
    21, // signal count

 // classinfo: key, value
    189, 190, 
    191, 192, 
    193, 194, 

// signal: name, argc, parameters, tag, flags
    195, 0, 255, 2, 5,
    196, 1, 256, 2, 5,
    198, 0, 259, 2, 5,
    199, 0, 260, 2, 5,
    200, 0, 261, 2, 5,
    201, 0, 262, 2, 5,
    202, 0, 263, 2, 5,
    203, 1, 264, 2, 5,
    205, 0, 267, 2, 5,
    206, 0, 268, 2, 5,
    207, 1, 269, 2, 5,
    208, 1, 272, 2, 5,
    210, 0, 275, 2, 5,
    211, 1, 276, 2, 5,
    1, 1, 279, 2, 5,
    4, 4, 282, 2, 5,
    34, 0, 291, 2, 5,
    35, 0, 292, 2, 5,
    9, 1, 293, 2, 5,
    11, 3, 296, 2, 5,
    45, 0, 303, 2, 5,

// slot: name, argc, parameters, tag, flags
    14, 1, 304, 2, 9,
    16, 1, 307, 2, 9,
    151, 1, 310, 2, 9,
    153, 1, 313, 2, 9,
    155, 1, 316, 2, 9,
    18, 1, 319, 2, 9,
    20, 1, 322, 2, 9,
    157, 1, 325, 2, 9,
    22, 1, 328, 2, 9,
    159, 1, 331, 2, 9,
    24, 1, 334, 2, 9,
    25, 1, 337, 2, 9,
    27, 4, 340, 2, 9,
    32, 0, 349, 2, 9,
    33, 1, 350, 2, 9,
    34, 0, 353, 2, 9,
    35, 0, 354, 2, 9,
    36, 0, 355, 2, 9,
    37, 0, 356, 2, 9,
    38, 0, 357, 2, 9,
    39, 0, 358, 2, 9,
    40, 0, 359, 2, 9,
    41, 2, 360, 2, 9,
    43, 1, 365, 2, 9,
    45, 0, 368, 2, 9,
    46, 0, 369, 2, 9,

// signal: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 197,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 204,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 21,
    QMetaType::Void, QMetaType::Bool, 209,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 23,
    QMetaType::Void, QMetaType::Bool, 3,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,
    QMetaType::Void,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 15,
    QMetaType::Void, QMetaType::Bool, 17,
    QMetaType::Void, QMetaType::UInt, 152,
    QMetaType::Void, QMetaType::QString, 154,
    QMetaType::Void, QMetaType::Bool, 156,
    QMetaType::Void, QMetaType::QString, 19,
    QMetaType::Void, QMetaType::Double, 21,
    QMetaType::Void, QMetaType::Int, 158,
    QMetaType::Void, QMetaType::Int, 23,
    QMetaType::Void, QMetaType::Bool, 160,
    QMetaType::Void, QMetaType::Bool, 3,
    QMetaType::Void, QMetaType::Int, 26,
    QMetaType::Void, QMetaType::QString, QMetaType::QVariant, 0x80000000 | 30, QMetaType::Int, 28, 29, 31, 21,
    QMetaType::Void,
    QMetaType::QVariant, QMetaType::QString, 10,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, QMetaType::QVariant, 10, 42,
    QMetaType::Void, QMetaType::Int, 44,
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    15, QMetaType::Bool, 0x01015003, 		 // bool AutoLoop
    17, QMetaType::Bool, 0x01015003, 		 // bool AutoPlay
    152, QMetaType::UInt, 0x03015003, 		 // uint BackColor
    154, QMetaType::QString, 0x0a015003, 		 // QString BaseURL
    156, QMetaType::Bool, 0x01015003, 		 // bool FullscreenEnabled
    47, QMetaType::Int, 0x02004001, 		 // int Length
    19, QMetaType::QString, 0x0a015003, 		 // QString MRL
    48, QMetaType::Bool, 0x01004001, 		 // bool Playing
    49, QMetaType::Int, 0x02005001, 		 // int PlaylistCount
    50, QMetaType::Int, 0x02005001, 		 // int PlaylistIndex
    21, QMetaType::Double, 0x06015003, 		 // double Position
    158, QMetaType::Int, 0x02015003, 		 // int StartTime
    23, QMetaType::Int, 0x02015003, 		 // int Time
    160, QMetaType::Bool, 0x01015003, 		 // bool Toolbar
    51, QMetaType::QString, 0x0a005001, 		 // QString VersionInfo
    3, QMetaType::Bool, 0x01015003, 		 // bool Visible
    26, QMetaType::Int, 0x02015003, 		 // int Volume
    161, 0x80000000 | 162, 0x00005001, 		 // IVLCAudio* audio
    163, 0x80000000 | 164, 0x00005001, 		 // IVLCInput* input
    165, 0x80000000 | 166, 0x00005001, 		 // IVLCMediaDescription* mediaDescription
    167, 0x80000000 | 168, 0x00005001, 		 // IVLCPlaylist* playlist
    135, 0x80000000 | 169, 0x00005001, 		 // IVLCSubtitle* subtitle
    170, 0x80000000 | 171, 0x00005001, 		 // IVLCVideo* video

 // enums: name, flags, count, data
    30, 0x0, 14, 443, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject VLCPlugin::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__VLCPlugin, 0, 0, 0 }
};

void *VLCPlugin::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::VLCPlugin"))
        return static_cast<void*>(const_cast<VLCPlugin*>(this));
    return QAxWidget::qt_metacast(_clname);
}
static const uint qt_meta_data_AXVLC__VLCPlugin2[] = {

 // content:
    7, // revision
    212,  // classname
    3, 14, // classinfo
    47, 20, // methods
    23, 370, // properties
    1, 439, // enums/sets
    0, 0, // constructors
    0, // flags
    21, // signal count

 // classinfo: key, value
    189, 190, 
    191, 194, 
    193, 192, 

// signal: name, argc, parameters, tag, flags
    195, 0, 255, 2, 5,
    196, 1, 256, 2, 5,
    198, 0, 259, 2, 5,
    199, 0, 260, 2, 5,
    200, 0, 261, 2, 5,
    201, 0, 262, 2, 5,
    202, 0, 263, 2, 5,
    203, 1, 264, 2, 5,
    205, 0, 267, 2, 5,
    206, 0, 268, 2, 5,
    207, 1, 269, 2, 5,
    208, 1, 272, 2, 5,
    210, 0, 275, 2, 5,
    211, 1, 276, 2, 5,
    1, 1, 279, 2, 5,
    4, 4, 282, 2, 5,
    34, 0, 291, 2, 5,
    35, 0, 292, 2, 5,
    9, 1, 293, 2, 5,
    11, 3, 296, 2, 5,
    45, 0, 303, 2, 5,

// slot: name, argc, parameters, tag, flags
    14, 1, 304, 2, 9,
    16, 1, 307, 2, 9,
    151, 1, 310, 2, 9,
    153, 1, 313, 2, 9,
    155, 1, 316, 2, 9,
    18, 1, 319, 2, 9,
    20, 1, 322, 2, 9,
    157, 1, 325, 2, 9,
    22, 1, 328, 2, 9,
    159, 1, 331, 2, 9,
    24, 1, 334, 2, 9,
    25, 1, 337, 2, 9,
    27, 4, 340, 2, 9,
    32, 0, 349, 2, 9,
    33, 1, 350, 2, 9,
    34, 0, 353, 2, 9,
    35, 0, 354, 2, 9,
    36, 0, 355, 2, 9,
    37, 0, 356, 2, 9,
    38, 0, 357, 2, 9,
    39, 0, 358, 2, 9,
    40, 0, 359, 2, 9,
    41, 2, 360, 2, 9,
    43, 1, 365, 2, 9,
    45, 0, 368, 2, 9,
    46, 0, 369, 2, 9,

// signal: parameters
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 197,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 204,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 21,
    QMetaType::Void, QMetaType::Bool, 209,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Int, 23,
    QMetaType::Void, QMetaType::Bool, 3,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 5, 6, 7, 8,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 10,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 10, 12, 13,
    QMetaType::Void,

// slot: parameters
    QMetaType::Void, QMetaType::Bool, 15,
    QMetaType::Void, QMetaType::Bool, 17,
    QMetaType::Void, QMetaType::UInt, 152,
    QMetaType::Void, QMetaType::QString, 154,
    QMetaType::Void, QMetaType::Bool, 156,
    QMetaType::Void, QMetaType::QString, 19,
    QMetaType::Void, QMetaType::Double, 21,
    QMetaType::Void, QMetaType::Int, 158,
    QMetaType::Void, QMetaType::Int, 23,
    QMetaType::Void, QMetaType::Bool, 160,
    QMetaType::Void, QMetaType::Bool, 3,
    QMetaType::Void, QMetaType::Int, 26,
    QMetaType::Void, QMetaType::QString, QMetaType::QVariant, 0x80000000 | 30, QMetaType::Int, 28, 29, 31, 21,
    QMetaType::Void,
    QMetaType::QVariant, QMetaType::QString, 10,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, QMetaType::QVariant, 10, 42,
    QMetaType::Void, QMetaType::Int, 44,
    QMetaType::Void,
    QMetaType::Void,

 // properties: name, type, flags
    15, QMetaType::Bool, 0x01015003, 		 // bool AutoLoop
    17, QMetaType::Bool, 0x01015003, 		 // bool AutoPlay
    152, QMetaType::UInt, 0x03015003, 		 // uint BackColor
    154, QMetaType::QString, 0x0a015003, 		 // QString BaseURL
    156, QMetaType::Bool, 0x01015003, 		 // bool FullscreenEnabled
    47, QMetaType::Int, 0x02004001, 		 // int Length
    19, QMetaType::QString, 0x0a015003, 		 // QString MRL
    48, QMetaType::Bool, 0x01004001, 		 // bool Playing
    49, QMetaType::Int, 0x02005001, 		 // int PlaylistCount
    50, QMetaType::Int, 0x02005001, 		 // int PlaylistIndex
    21, QMetaType::Double, 0x06015003, 		 // double Position
    158, QMetaType::Int, 0x02015003, 		 // int StartTime
    23, QMetaType::Int, 0x02015003, 		 // int Time
    160, QMetaType::Bool, 0x01015003, 		 // bool Toolbar
    51, QMetaType::QString, 0x0a004001, 		 // QString VersionInfo
    3, QMetaType::Bool, 0x01015003, 		 // bool Visible
    26, QMetaType::Int, 0x02015003, 		 // int Volume
    161, 0x80000000 | 162, 0x00005001, 		 // IVLCAudio* audio
    163, 0x80000000 | 164, 0x00005001, 		 // IVLCInput* input
    165, 0x80000000 | 166, 0x00005001, 		 // IVLCMediaDescription* mediaDescription
    167, 0x80000000 | 168, 0x00005001, 		 // IVLCPlaylist* playlist
    135, 0x80000000 | 169, 0x00005001, 		 // IVLCSubtitle* subtitle
    170, 0x80000000 | 171, 0x00005001, 		 // IVLCVideo* video

 // enums: name, flags, count, data
    30, 0x0, 14, 443, 

 // enum data: key, value
    53, uint(AXVLC::VLCPlayListInsert),
    54, uint(AXVLC::VLCPlayListInsertAndGo),
    55, uint(AXVLC::VLCPlayListReplace),
    56, uint(AXVLC::VLCPlayListReplaceAndGo),
    57, uint(AXVLC::VLCPlayListAppend),
    58, uint(AXVLC::VLCPlayListAppendAndGo),
    59, uint(AXVLC::VLCPlayListCheckInsert),
    60, uint(AXVLC::VLCPlayListInsert1),
    61, uint(AXVLC::VLCPlayListInsertAndGo2),
    62, uint(AXVLC::VLCPlayListReplace3),
    63, uint(AXVLC::VLCPlayListReplaceAndGo4),
    64, uint(AXVLC::VLCPlayListAppend5),
    65, uint(AXVLC::VLCPlayListAppendAndGo6),
    66, uint(AXVLC::VLCPlayListCheckInsert7),
    0 // eod
};

const QMetaObject VLCPlugin2::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_AXVLC__VLCPlugin2, 0, 0, 0 }
};

void *VLCPlugin2::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "AXVLC::VLCPlugin2"))
        return static_cast<void*>(const_cast<VLCPlugin2*>(this));
    return QAxWidget::qt_metacast(_clname);
}

